
    create table vagas_online.tb_candidaturas (
        data_candidatura date,
        status smallint check (status between 0 and 2),
        user_id bigint not null,
        vaga_id bigint not null unique,
        primary key (user_id, vaga_id)
    );

    create table vagas_online.tb_notificacoes (
        lida boolean,
        id bigint generated by default as identity,
        instante TIMESTAMP WITHOUT TIME ZONE,
        user_id bigint,
        texto varchar(255),
        primary key (id)
    );

    create table vagas_online.tb_password_recover (
        expiration timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        email varchar(255) not null,
        token varchar(255) not null,
        primary key (id)
    );

    create table vagas_online.tb_role (
        id bigint generated by default as identity,
        authority varchar(255),
        primary key (id)
    );

    create table vagas_online.tb_user (
        id bigint generated by default as identity,
        email varchar(255) unique,
        endereco varchar(255),
        nome varchar(255),
        password varchar(255),
        profissao varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    create table vagas_online.tb_user_role (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table vagas_online.tb_vagas (
        data_criacao_vaga DATE,
        data_realizacao_diaria date,
        status smallint check (status between 0 and 1),
        valor_diaria float(53),
        id bigint generated by default as identity,
        descricao TEXT,
        local varchar(255),
        requisitos varchar(255),
        titulo varchar(255),
        primary key (id)
    );

    alter table if exists vagas_online.tb_candidaturas 
       add constraint FK44h81va4ilyesi27ob670ln8i 
       foreign key (vaga_id) 
       references vagas_online.tb_vagas;

    alter table if exists vagas_online.tb_candidaturas 
       add constraint FKqjrndp6a91it2iyaaqimaeivn 
       foreign key (user_id) 
       references vagas_online.tb_user;

    alter table if exists vagas_online.tb_notificacoes 
       add constraint FK3myd1mrnvs13g2gig8pmn4klc 
       foreign key (user_id) 
       references vagas_online.tb_user;

    alter table if exists vagas_online.tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references vagas_online.tb_role;

    alter table if exists vagas_online.tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references vagas_online.tb_user;
       
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_role (authority) VALUES ('ROLE_CANDIDATO');
INSERT INTO tb_role (authority) VALUES ('ROLE_RH');
INSERT INTO tb_role (authority) VALUES ('ROLE_GERENTE');

INSERT INTO tb_user (nome, email, password, profissao, telefone, endereco) VALUES ('Jardel Rodrigues', 'rodriguesjardel96@gmail.com', '$2a$10$Qk8KkAC6KsqI2OWRmPica.hNl5ZDWZDzdTa1sHyd25BtVsmHcW/5y', 'Desenvolvedor de software', '(61) 994229903', 'Rua 110 Quandra 320 Lote 10');
INSERT INTO tb_user (nome, email, password, profissao, telefone, endereco) VALUES ('Maria silva', 'maria@gmail.com', '$2a$10$Qk8KkAC6KsqI2OWRmPica.hNl5ZDWZDzdTa1sHyd25BtVsmHcW/5y','Eletricista', '(61) 996542587', 'Rua 10 Quandra 30 Lote 11');
INSERT INTO tb_user (nome, email, password, profissao, telefone, endereco) VALUES ('Alex Alves', 'alex@gmail.com', '$2a$10$Qk8KkAC6KsqI2OWRmPica.hNl5ZDWZDzdTa1sHyd25BtVsmHcW/5y', 'Segurança', '(61) 984562547', 'Rua 15 Quandra 50 Lote 113');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);

INSERT INTO tb_notificacoes (user_id, texto, instante, lida) VALUES (1, 'Candidatura enviada com sucesso', TIMESTAMP WITH TIME ZONE '2024-8-31T13:00:00Z', true);
INSERT INTO tb_notificacoes (user_id, texto, instante, lida) VALUES (2, 'Candidatura aprovada', TIMESTAMP WITH TIME ZONE '2024-08-31T13:00:00Z', false);

INSERT INTO tb_vagas (titulo, descricao, requisitos, data_criacao_vaga, local, valor_diaria, status) VALUES ('Auxiliar de serviços gerais', 'Auxiliar de serviços gerais', 'Não se aplica', TIMESTAMP WITH TIME ZONE '2024-08-31T13:00:00Z', 'Gama', 120.00, 1);
INSERT INTO tb_vagas (titulo, descricao, requisitos, data_criacao_vaga, local, valor_diaria, status) VALUES ('Sergurança patrimonial', 'Sergurança patrimonial', 'Ter experiencia com segurança', TIMESTAMP WITH TIME ZONE '2024-08-31T13:00:00Z', 'Park Shopping', 250.00, 1);

INSERT INTO tb_candidaturas (user_id, vaga_id, data_candidatura, status) VALUES (2, 1, TIMESTAMP WITH TIME ZONE '2024-08-31T13:00:00Z', 0);
INSERT INTO tb_candidaturas (user_id, vaga_id, data_candidatura, status) VALUES (3, 2, TIMESTAMP WITH TIME ZONE '2024-08-31T13:00:00Z', 0);
